#!/bin/bash

if [[ -z $1 ]]; then
	echo "No package specified."
	exit
fi

CODE=$(curl -s -o /dev/null -w "%{http_code}" https://aur.archlinux.org/packages/$1)

if [[ $CODE == 404 ]]; then
	echo "This package wasn't found."
	exit
fi

cd /tmp
git clone https://aur.archlinux.org/$1.git

cd $1
makepkg -si

cd -
rm -rf /tmp/$1
