#!/bin/bash

if [[ $(id -u) == 0 ]]; then
	echo "Don't run my with root permissions."
	exit
fi

if [[ $1 == "-A" || $1 == "--aur" ]]; then

	if [[ -z $2 ]]; then
		echo "No package specified."
		exit
	fi

	CODE=$(curl -s -o /dev/null -w "%{http_code}" https://aur.archlinux.org/packages/$2)

	if [[ $CODE == 404 ]]; then
		echo "This package wasn't found."
		exit
	fi

	cd /tmp
	git clone https://aur.archlinux.org/$2.git

	cd $2
	makepkg -si

	cd -
	rm -rf /tmp/$2

elif [[ $1 == "-h" || $1 == "--help" ]]; then

echo "utilisation :  luna <opération> [...]
opérations :
	luna {-h --help}
	luna {-V --version}
	luna {-D --database} <options > <paquet(s)>
	luna {-F --files}    [options ] [fichier(s)]
	luna {-Q --query}    [options ] [paquet(s)]
	luna {-R --remove}   [options ] <paquet(s)>
	luna {-S --sync}     [options ] [paquet(s)]
	luna {-T --deptest}  [options ] [paquet(s)]
	luna {-U --upgrade}  [options ] <fichier(s)>
	luna {-A --aur}      [paquet(s)]

utiliser « luna {-h --help} » avec une opération pour afficher les options disponibles."

else sudo pacman $*; fi
